### ISSUE TITLE
Project download in Excel format

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#1074]
enhancement to the data download (export) to an Excel file function to –
 
·         Be able to export, i.e. download a displayed list of ‘Natural resource management works projects’ to an MS Excel file based on the format of the attached spreadsheet.
 
·         The displayed list may be from –
o   selecting the ‘All projects’ or the ‘My projects’ button
o   using the Filters or the ‘Search’ function.
 
·         In the attached spreadsheet I have included the row headings we would use, as per the row shaded in yellow, plus I have identified the data item we would seek to have loaded into each column and cell, as shaded in green.
 
·         For the Status field, insert –
o   ‘Planned’ where todays date is less than the project start date
o   ‘Current’ where todays date is equal to or greater than the project start date and equal to or less than the project end date
o   ‘Completed’ where todays date is greater than the project end date.

**Comment by pbrenton** [comment]
Was this feature restricted to only OGBR hub admins? Would be a good feature to make available to all hubs as I have had a request from ACSA management to also provide XLSX project list download.

Can the reef-projects only restriction please be lifted so that projects listed in a hub can be downloaded from the context of that hub?
