### ISSUE TITLE
PF: Allow Search by partial words

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#1135]
Currently the PF Search text box allows searching only by matching whole words contained in the metadata.

For example a search for "citi" will yield no results however "citizen" will.

Adjust search functionality to allow search on partial words or substrings across the project metadata fields.

 The search must require at least partial words of 3 characters.

Analyze what is the current ranking mechanism and how this will be affected.

A few details of current behaviour:

"Citizen fri" yields no results, "Citizen friends" comes with 26 results

After this ticket is implemented the search for "Citizen fri" must return at least 26 results.

**Comment by javier-molina** [comment]
This is going on the right track.

I can see at the moment the search is appending a * so essentially it searches for startswith.

The only remaining job is to do the same at the beginning, ie, prepending  a * at the start of the phrase to fulfill the requirement of substring (contains) search.

**Comment by chrisala** [comment]
Is this how we want the search to behave?  That is the behaviour you more expect from a real time filter rather than enter search term and press enter?

Part of the problem is that the search is treated as a lucene query string which means it's parsed for things like "AND" / "OR" / quoted strings etc.
Appending wildcards to the front of a search string can result in (computationally) expensive searches as well as potentially break the expected behaviour of the parser.
Elastic / lucene also supports fuzzy searches via distance matching (I think using a ~).  
"Citizen fri" should really be tokenizing and getting some matches from "Citizen" - the fact it's not might just mean it's doing a phrase match, which might be the result of the query string query.  
It might just be better to change the default search to a normal search and move the lucene search string to an advanced search or something?

**Comment by temi** [comment]
Added a hub option to enable partial search.
