### ISSUE TITLE
Need some sort of introduction after creating new project

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#122]
At the moment you end up on your saved tab (i.e. the last tab you visited from any project) on the new project page.

**Comment by pbrenton** [comment]
New changes to the survey configuration workflow that Sathish has just done may help to address this concern. These include adding next/back buttons to each step, adding some more descriptive info for the workflow process, moving the publish step from the survey info tab to its own tab, and adding onPublish navigation to the survey list page.

I'm inclined to see how this goes first and then consider whether an information page to land on after publishing would work better. It is a good idea though.

**Comment by pbrenton** [comment]
Maybe we can do this with a new static page (ALA ADMIN editable) which is opened after successful submit of the project metadata page for internal projects only. This would allow for content to be easily tweaked and managed.

Ideally this page would only be needed once when the project is created rather than on subsequent edits of the project metadata page too.

**Comment by m-r-c** [comment]
I have added a new page, where the content comes from the 'fielddata.citizenScience.newProjectIntro' static text.

https://github.com/AtlasOfLivingAustralia/biocollect/pull/280
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-19
