### ISSUE TITLE
Cannot manually enter coordinates for site

### ISSUE THREAD

**Issue by matildastevenson** [AtlasOfLivingAustralia/biocollect#1227]
![Screen Shot 2019-11-08 at 12 20 54 pm](https://user-images.githubusercontent.com/25336120/68444422-da259700-022a-11ea-90b7-d3a178766c05.png)

Coordinates on right do not matched coordinates entered on left. Manually changing coordinates on the right does not change the site location. The difference is not a rounding error, and in some cases the difference between the entered and actual coordinates is >1km

**Comment by matilda2812** [comment]
It is not possible to manually enter or edit coordinates when creating a site, either via the Sites interface or within a survey form. This issue is compounded by the search functionality not mapping coordinates searched for to the site coordinates (see above).
Although it is possible to enter coordinates on the right as shown in the screenshot above, this change does not update the site coordinates. 
The above issues mean that there is no way to accurately create a site via the interface, which is frustrating for users.
