### ISSUE TITLE
Preview is not working for PDF resource types

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#219]

**Comment by chrisala** [comment]
In dev this won't work because dev is configured to look for uploads on ecodata-test. (so that the existing project images etc still work)
In test this wasn't working because the resource viewer makes an ajax call to ecodata to load the PDF which was being denied due to cross origin policy.
I've added configuration to ecodata to set the CORS headers for requests from the ala.org.au subdomain.
