### ISSUE TITLE
my data page is viewable when not logged in

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#220]
my data page is viewable when not logged in. expected behaviour is to redirect to log in page.
also, /project/citizenScience - home page address, redirects to login. expected behaviour is to show the project finder page.

**Comment by sat01a** [comment]
The scope of the ticket needs to be expanded to cover other pages too, so that consistency can be maintained across the system.
Following requirements needs to be ironed out: (May be planning meeting?)
1, Top bar menus (My Projects, My Data) needs to be visible when the user is not logged in?
2. Do we redirect to login page or forward to home page with instruction with Access denied message (Similar to protected page page?)

**Comment by temi** [comment]
change is in ala-install repo
