### ISSUE TITLE
Add audit feature to admin only options for projects

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#222]
Need to include the audit feature for projects as implemented in MERIT

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-16

**Comment by sat01a** [comment]
Add some notes in upsource.

Also, do you think we can make the audit message load on demand and by pagination. Otherwise project page load time will increase as more records/activities are added.

Note: In MERIT its just handful of activities, in biocollect survey based projects will produce more activities.

**Comment by temi** [comment]
created a new issue for pagination, sorting and filtering #281
