### ISSUE TITLE
Allow mouse-based zoom on "create site" map

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#238]
Should be able to zoom the map using both mouse wheel scroll and bounding box on the create site page.

**Comment by m-r-c** [comment]
I have updated the ALA Map plugin and added http://cliffcloud.github.io/Leaflet.Sleep/, which gives the following behaviour:

1. The map 'sleeps' (i.e. stops receiving input from the mouse) when the mouse has been outside the map for more than 750ms. 
1. Clicking the map, or hovering the mouse over it for 750ms 'wakes' the map up so it starts receiving input from the mouse again.

This lets the user scroll over the map when scrolling quickly down the page (which was why the mouse zoom was originally disabled because it stopped the page from scrolling), but also lets them control the map zoom with the mouse when they want.

The times, and whether a mouseover will wake the map or just a click, are configurable. We can also display a message over the map when it is 'sleeping' (not currently doing that). The ALA Map plugin doco has been updated accordingly.
