### ISSUE TITLE
Organisation page - change name of sites tab to "Map" and zoom to extent of all projects

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#366]
The "sites" tab is mis-named as it really relates to project areas. Would be better to name it simply "Map".

Also, it does not currently zoom to the combined extent of all project areas, but it should.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-64

**Comment by m-r-c** [comment]
There were issues with drawing the map with multiple project areas: the map lost the base layer (or some of its tiles), and zoom controls broke.

This appears to be caused by https://github.com/Leaflet/Leaflet/issues/3249. As a workaround, I have disabled animations on pan and zoom.

https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-7
