### ISSUE TITLE
Image Gallery - add more details

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#411]
Add Project Name, Activity Name to photo metadata.
Add link to project and activity when viewing enlarged image.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-84
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-23

**Comment by m-r-c** [comment]
I think there are some problems here:

1. When you attach a small image, the thumbnail on the Images tab zooms in, but the popup shows the original small image
1. The links on the popup cannot be tabbed onto (tested in Chrome)
1. The caption sits on top of the image (bad for small images)
1. The mouse-over tooltip cannot be seen without the mouse (e.g. screen reader or mobile) and contains info that is not visible on the popup (name and date)

Suggestions:

1. The popup should include the metadata in a panel below the image rather than as a caption (also show the date and name)
1. Set a minimum scaled size for the image in the popup so that it is always bigger than the thumbnail
1. Apply the same styles to the thumbnail as those used for the project logo on the project finder (since that already correctly handles aspect ratios etc).

**Comment by m-r-c** [comment]
Looks good. The only problem I can see is that the initial zoom level on the leaflet view is quite small. For example, attach the Birds in Backyards project logo. When viewed in the image viewer, it is tiny (much smaller than the actual image size). Can you set the initial zoom such that either the image fills the whole panel, or at least so that it matches the actual size of the image?

**Comment by m-r-c** [comment]
I've also noticed that the image is hidden behind the input fields on narrow screens/mobile

**Comment by temi** [comment]
that is the limitation of leaflet. Zooming in for small images would mean zoom level for large images will be unacceptable. I think practically we will not have such small images for sightings. Hence I do not think it would be necessary to accommodate it. 

About hidden image, can you sent me a picture and the steps to replicate it.

**Comment by m-r-c** [comment]
I think all you need to do is add ```map.fitBounds(bounds);``` to imageviewer.gsp above the call to setMaxBounds.

The hidden image problem is on the data entry pages: attach an image to a survey form, then either resize the window to make it very narrow or use Chrome's device mode to set it to mobile.

**Comment by temi** [comment]
ok done that.

Hidden image problem is not an image gallery issue. It is a image data type issue. Raise a separate bug for it.
