### ISSUE TITLE
Survey configuration - Sites - Change buttons

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#43]
Change "Add" in green buttons to ">>" and "Remove in red buttons to "<<", but use these words as alt-text on the respective buttons.

**Comment by temi** [comment]
i think this interface needs some improvement. It was very hard for me to understand how it operates. I was able to do the job only because the issue accurately describes what has to be done.
Some suggestions are:
* make both add and remove button visible but disable the button that cannot be acted on. Currently, the logic hides the button when there is nothing to add or remove.
* bringing the two columns closer together
* UI additions to emphasise them as two columns
* Some text to describe the purpose of this tab
