### ISSUE TITLE
Uncaught error on admin> project edit for Redmap project

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#437]
Error preventing the Redmap project edit from opening the project metadata page.

See http://biocollect.ala.org.au/project/edit/4a6ed292-3e60-45b8-9a95-26f6ffe31a81

**Comment by javier-molina** [comment]
@pbrenton  this is caused by organisations (both running and in association) that have a name longer than 64 characters. This is a very restrictive value hardcoded , I will increase that to 256 unless I hear a different value from you.

I will also add validations on the UI so users don't enter a name longer than 256.

Below, only for reference, is the organisation names we currently have in production, looks like there is nothing above 100 chars.
`
> db.getCollection('organisation').find({name: {$type: 2}, $where: "this.name.length > 64"}, {name:1,_id:0})
{ "name" : "Department of Sustainability, Environment, Water, Population and Communities" }
{ "name" : "New Zealand National Institute of Water and Atmospheric Research " }
{ "name" : "Tasmanian Department of Primary Industries, Parks, Water and Environment" }
{ "name" : "University of Tasmania - Institute for Marine and Antarctic Studies" }
{ "name" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
> db.getCollection('project').find({organisationName: {$type: 2}, $where: "this.organisationName.length > 64"}, {organisationName:1,_id:0})
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Department of Environment Climate Change Energy and Water (ACT) Departmental" }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "MORNINGTON PENINSULA AND WESTERN PORT BIOSPHERE RESERVE FOUNDATION LTD" }
{ "organisationName" : "OZ GREEN-GLOBAL RIVERS ENVIRONMENTAL EDUCATION NETWORK (AUSTRALIA) INCORPORATED" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "Mullumbimby Centre for Sustainable Living and Environmental Education inc." }
{ "organisationName" : "Farm Tree and Landcare Association - Boolarra South Landcare Group" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
Type "it" for more
> it
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Whitsunday Rivers Integrated Catchment Management Association Inc" }
{ "organisationName" : "C.E. Driver & The EBA Trust & The Estate of the Late Roy Henry Driver" }
{ "organisationName" : "Office of Environment and Heritage, National Parks and Wildlife Service" }
{ "organisationName" : "DEPARTMENT OF TRADE & INVESTMENT REGIONAL INFRASTRUCTURE AND SERVICES" }
{ "organisationName" : "Tamar Region Natural Resource Management Strategy Reference Group Inc." }
{ "organisationName" : "Office of Environment and Heritage - NSW National Parks and Wildlife Service" }
{ "organisationName" : "Department of Trade and Investment Regional Infrastructure and Services" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Tamar Region Natural Resource Management Strategy Reference Group Inc." }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "NSW Office of Environment and Heritage, National Parks and Wildlife Service" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated " }
{ "organisationName" : "Tasmanian Department of Primary Industries, Parks, Water and Environment" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
Type "it" for more
> it
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "Friends of Caboolture Region Environmental Education Centre Association Inc" }
{ "organisationName" : "Tamar Region Natural Resource Management Strategy Reference Group Inc." }
{ "organisationName" : "Department of Trade and Investment Regional Infrastructure and Services" }
{ "organisationName" : "University of Tasmania - Institute for Marine and Antarctic Studies" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "Office of Environment and Heritage - National Parks and Wildlife Service" }
{ "organisationName" : "Department of Land Resource Management Northern Territory of Australia" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Goolwa To Wellington Local Action Planning Association Incorporated" }
{ "organisationName" : "South Australian Murray-Darling Basin Natural Resources Management Board" }
{ "organisationName" : "Tamar Region Natural Resource Management Strategy Reference Group Inc" }
{ "organisationName" : "Goolwa to Wellington Local Action Planning Association Incorporated" }
{ "organisationName" : "Goolwa to Wellington Local Action Planning Association Incorporated" }
{ "organisationName" : "Goolwa to Wellington Local Action Planning Association Incorporated" }
{ "organisationName" : "Department of Trade and Investment Regional Infrastructure and Services" }
>
`

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-143
