### ISSUE TITLE
Fix https mixed content issue

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#459]
Note from @matthewandrews 

To fix the mixed-content problem, we will need a few things I think - set headerAndFooterBaseURL to https, change the favicon URL to https, and (the main one) make ecodata available via https, and change the project logo URL base (ecodata) to the https version.

**Comment by javier-molina** [comment]
Issues from login page

- Mixed Content: The page at 'https://auth.ala.org.au/cas/login?service=https://devt.ala.org.au:9087/biocollect/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://bie.ala.org.au/search'. This endpoint should be made available over a secure connection.

Issues from main page
- Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/' was loaded over HTTPS, but requested an insecure image 'http://www2.ala.org.au/commonui-bs2/images/NCRIS_mono.svg'. This content should also be served over HTTPS.
- (index):456 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/' was loaded over HTTPS, but requested an insecure image 'http://www2.ala.org.au/commonui-bs2/images/aus_initiative_stacked.svg'. This content should also be served over HTTPS.
- (index):464 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/' was loaded over HTTPS, but requested an insecure image 'http://www2.ala.org.au/commonui-bs2/images/GBIF-2015-cropped.png'. This content should also be served over HTTPS.
- (index):470 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/' was loaded over HTTPS, but requested an insecure image 'http://www2.ala.org.au/commonui-bs2/images/creativecommons.png'. This content should also be served over HTTPS.
- (index):1 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/' was loaded over HTTPS, but requested an insecure image 'http://www.ala.org.au/wp-content/themes/ala2011/images/favicon.ico'. This content should also be served over HTTPS.
- (index):514 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort' was loaded over HTTPS, but requested an insecure script 'http://www.ala.org.au/wp-content/themes/ala-wordpress-theme/js/browser-update-org.min.js?ver=2015.11'. This request has been blocked; the content must be served over HTTPS.$buo_f @ (index):514
- :9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort:1 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort' was loaded over HTTPS, but requested an insecure image 'http://devt.ala.org.au:8080/ecodata/document/download?filename=2016-03/thumb_2_1.png'. This content should also be served over HTTPS.
- :9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort:1 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort' was loaded over HTTPS, but requested an insecure image 'http://devt.ala.org.au:8080/ecodata/document/download?filename=2016-02/1_Glass_4.jpg'. This content should also be served over HTTPS.
- :9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort:1 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort' was loaded over HTTPS, but requested an insecure image 'http://scistarter.com/media/projects/Beak_background.jpg'. This content should also be served over HTTPS.
- :9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort:1 Mixed Content: The page at 'https://devt.ala.org.au:9087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort' was loaded over HTTPS, but requested an insecure image 'http://devt.ala.org.au:8080/ecodata/document/download?filename=2016-02/thumb_1_1-12-2015_4-41-48_PM.jpg'. This content should also be served over HTTPS.
- download:1 GET http://devt.ala.org.au:8080/ecodata/document/download?filename=2016-02/1_Glass_4.jpg 404 (Not Found)

**Comment by matthewandrews** [comment]
The search form can submit to https://bie.ala.org.au/search

The commonui URLs can be changed to https://www.ala.org.au/commonui-bs2/ etc (or www2, either will work).

**Comment by javier-molina** [comment]
yeap, most things can be changed to https, I added the comment as a personal checklist of what I need to address. 

I can tell that scistarter.com could be a problem, it serves https but the certificate is for a different domain name.

**Comment by javier-molina** [comment]
Not available via https:

- biocache.baseURL=http://biocache.ala.org.au
- spatial.baseURL=http://spatial.ala.org.au

**Comment by javier-molina** [comment]
@sat01a, @chrisala 

I wanted to bring to your attention what I think it is the last scenario for Biocollect to go fully https.

When creating organisations from the **'This project is run in association with '** the logo for the site is a URL that is rendered verbatim when showing the About page for a project. If the user adds a non-https url we will have the issue of the browser complaning about the mixed content type.

See images below for reference 

![image](https://cloud.githubusercontent.com/assets/8326394/15038134/78335426-12e4-11e6-802b-6448c1437bde.png)

![image](https://cloud.githubusercontent.com/assets/8326394/15038123/6ed507a8-12e4-11e6-85c2-770794915827.png)


Moving forward I can think on possible solutions or accepting the lack of them but I need your input given that this will, in some cases, affect ecodata backend, and I don't know what the implications will be for other systems apart from biocollect


1. Do nothing
- Associated organisations (not in the global list) as far as I can tell are used only locally in a project to display basic information in the project about page. 
- The mixed content issue will be a direct result of project admin own action, will his users can accept those warnings?

2. Register associated organisations the same way as organisation running the project
- The structure in ecodata would be preserved but the list of global organisations could potentially grow significantly. In any case organisations can already be created directly in Organisation running the project section.
- We would need to migrate existing project specific organisations to the organisation collection in the database, including sourcing the logos where available.

3. Modify the associatedOrgs field for a project in the database to have a pointer to the Document storing the logo instead of the Url.
- The format of an associatedOrgs entry will be similar to an entry for  Organisation collection where the metadata is stored  there and one or more Document entries are created for files, such as the logo.
- This would be the most invasive approach and will also require a migration of existing data.


Can you please let me know your thoughts?

Also please let me know if anything is unclear.

**Comment by sat01a** [comment]
Hi @javier-molina,

In project creation page, I would suggest to add extra validation rule to check for https. Also, while rendering the image, we should make sure we render only https based urls.

There should be only handful of projects which will have this issue, we can update them manually. 

Only Biocollect will have this issue, MERIT doesn't use this field.

Thanks

**Comment by javier-molina** [comment]
content coming from spatial.org.au  (esssentially any page containing a map, visible or not) will still be displaying a warning in the browser.

This will be addressed on #519

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-10
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-139
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-51 

Will release ala-map-plugin 1.3.1 and issue pull requests once the reviewer is happy with the changes.

Please also keep an eye on previous comment above for the scope of this ticket.

**Comment by javier-molina** [comment]
As per  https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/4OnLZlP7NvU 

Tomcat needs to know the original scheme used to call a page so the grails resources plugin can build urls properly.

This config needs to be applied to server.xml for biocollect production during release.

`<Valve className="org.apache.catalina.valves.RemoteIpValve"
   protocolHeader="X-Forwarded-Proto"
   remoteIpHeader="X-Forwarded-For"
   proxiesHeader="X-Forwarded-By"
   internalProxies="xxx\.xxx\.xxx\.xxx"


/>`

internalProxies address is the Apache proxy ip address, usually the same host as tomcat.

Ansibible does not require it as it uses AJP connector however SSL still needs to be properly enabled as per #521

**Comment by sat01a** [comment]
Pls update ansible config to include tomcat config change.

**Comment by javier-molina** [comment]
Remaining changes

https://upsource.ala.org.au/ala-install/review/AI-CR-13 
https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/7c0e22705e1de087be6566ee4d42c27d8d45e38c
