### ISSUE TITLE
Server side validation for organisation creation/update.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#464]

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ecodata/tree/biocollect-464

**Comment by adam-collins** [comment]
moved validation from ecodata to biocollect
https://github.com/AtlasOfLivingAustralia/biocollect/tree/biocollect-464

**Comment by adam-collins** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-124

**Comment by javier-molina** [comment]
@adam-collins 
A couple of examples that will break, probably you want to validate id as using [groovy truth|http://groovy-lang.org/semantics.html#Groovy-Truth] rather than just checking for null


description is empty yet the record is created
![image](https://cloud.githubusercontent.com/assets/8326394/13910028/f6d11752-ef6f-11e5-9c02-389b691f2303.png)


name is empty but the biocollect validator bypasses that, it is instead the ecodata contraints that prevents the record from being created.

![image](https://cloud.githubusercontent.com/assets/8326394/13910031/026b4d62-ef70-11e5-984d-fe71e36b6bb8.png)
