### ISSUE TITLE
Project metadata tag storing, but not displaying

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#688]
The "Participate at home" project metadata tag in the citizen science project hub can be selected and the selection does store on save, but the selection is being lost when the metadata template is edited.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-70

**Comment by javier-molina** [comment]
This needs more work.

When choosing Can people participate in this project from home? option the back end will store isHome = false all the time and the About page apparently displays the tag based on whether isHome is not null instead of isHome being true.

In summary once the Can people participate in this project from home? is selected for a project, there is no way to make it disappear from the about page.

**Comment by sat01a** [comment]
Fixed.
